const CASE_IMAGE_FILES: Record<string, string> = {
  kilowatt_case: "Kilowatt_Case.webp",
  dreams_nightmares_case: "Dreams_&_Nightmares_Case.webp",
  fracture_case: "Fracture_Case.webp",
  revolution_case: "Revolution_Case.webp",
  revolver_case: "Revolver_Case.webp",
  recoil_case: "Recoil_Case.webp",
  operation_breakout_weapon_case: "Operation_Breakout_Weapon_Case.webp",
  fever_case: "Fever_Case.webp",
  csgo_weapon_case: "CS_GO_Weapon_Case.webp",
  glove_case: "Glove_Case.webp",
  gallery_case: "Gallery_Case.webp",
  clutch_case: "Clutch_Case.webp",
  spectrum_2_case: "Spectrum_2_Case.webp",
  snakebite_case: "Snakebite_Case.webp",
  prisma_2_case: "Prisma_2_Case.webp",
  prisma_case: "Prisma_Case.webp",
  operation_hydra_case: "Operation_Hydra_Case.webp",
  gamma_case: "Gamma_Case.webp",
  chroma_2_case: "Chroma_2_Case.webp",
  operation_phoenix_weapon_case: "Operation_Phoenix_Weapon_Case.webp",
  gamma_2_case: "Gamma_2_Case.webp",
  spectrum_case: "Spectrum_Case.webp",
  chroma_3_case: "Chroma_3_Case.webp",
  chroma_case: "Chroma_Case.webp",
  cs20_case: "CS20_Case.webp",
  csgo_weapon_case_2: "CS_GO_Weapon_Case_2.webp",
  csgo_weapon_case_3: "CS_GO_Weapon_Case_3.webp",
  danger_zone_case: "Danger_Zone_Case.webp",
  esports_2013_case: "eSports_2013_Case.webp",
  esports_2013_winter_case: "eSports_2013_Winter_Case.webp",
  esports_2014_summer_case: "eSports_2014_Summer_Case.webp",
  falchion_case: "Falchion_Case.webp",
  horizon_case: "Horizon_Case.webp",
  huntsman_weapon_case: "Huntsman_Weapon_Case.webp",
  operation_bravo_case: "Operation_Bravo_Case.webp",
  operation_broken_fang_case: "Operation_Broken_Fang_Case.webp",
  operation_riptide_case: "Operation_Riptide_Case.webp",
  operation_vanguard_weapon_case: "Operation_Vanguard_Weapon_Case.webp",
  operation_wildfire_case: "Operation_Wildfire_Case.webp",
  shadow_case: "Shadow_Case.webp",
  shattered_web_case: "Shattered_Web_Case.webp",
  winter_offensive_weapon_case: "Winter_Offensive_Weapon_Case.webp",
};

export function caseImagePath(caseId: string): string {
  const file = CASE_IMAGE_FILES[caseId];
  return file ? `/assets/img/cases/${encodeURIComponent(file)}` : "";
}
